[project]
name = "spautofy"
version = "0.1.0"
description = "Spotify AI CLI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "openai>=2.8.1",
    "requests",
    "psycopg2-binary",
]
